config/routes.rb
Rails.application.routes.draw do
  
  # Index root path
  root "pages#home"
  # Setting get of pages/home with controller
  get 'pages/home', to: 'pages#home'
  
  # Nested routes Recipes and then Comments inside
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  # Signup path with Chefs controller
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  # Session Controller routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Ingredient route minus the destroy action in Fixings controller
  resources :fixings, except: [:destroy]
  
  # Setting up Action Cable server
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/models/fixing.rb
class Fixing < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_fixings
  has_many :recipes, through: :recipe_fixings
end

app/controllers/fixings_controller.rb
class FixingsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]
  
  def index
    @fixings = Fixing.paginate(page: params[:page], per_page: 10)
  end
  
  def show
    @fixing_recipes = @fixing.recipes.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @fixing = Fixing.new
  end
  
  def edit
  
  end
  
  def create
    @fixing = Fixing.new(fixing_params)
    if @fixing.save
      flash[:success] = "Ingredient was successfully created"
      redirect_to fixing_path(@fixing)
    else
      render 'new'
    end
  end
  
  def update
    if @fixing.update(fixing_params)
      flash[:success] = "Ingredient was updated successfully"
      redirect_to @fixing
    else
      render 'edit'
    end
  end
  
  private
  
  def fixing_params
    params.require(:fixing).permit(:name)
  end
  
  def set_ingredient
    @fixing = Fixing.find(params[:id])
  end
  
  def require_admin
    if !logged_in? || (logged_in? && !current_chef.admin?)
      flash[:danger] = " Only admin users can perform that action"
      redirect_to fixing_path
    end
  end
  
end

app/views/fixings/_fixing.html.erb
<span class="badge alert-danger"><%= link_to fixing.name.capitalize, fixing_path(fixing) %> &nbsp; </span>

app/views/fixings/_form.html.erb
<%= render 'shared/errors', obj: @fixing %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@fixing, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter Ingredient", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@fixing.new_record? ? "Add Ingredient" : "Update Ingredient",
                                    class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/fixings/edit.html.erb
<%= render 'shared/page_title', title: "Edit an existing ingredient" %>

<%= render 'form' %>

app/views/fixings/index.html.erb
<% @title = "Available Ingredients for Dinner Ideas" %>
<%= render 'shared/page_title', title: "Available Ingredients" %>
<div align="center">
  <%= will_paginate %>
  <% @fixings.each do |ing| %>
      <ul class="listing">
        <div class="row">
          <div class="well col-md-4 col-md-offset-4">
            <li class="chef-title"><%= link_to ing.name.capitalize, fixing_path(ing) %></li>
            <li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>
            <% if logged_in? && current_chef.admin? %>
              <li><%= link_to "Edit this ingredient", edit_fixing_path(ing) %></li>
            <% end %>
          </div>
        </div>
      </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/fixings/new.html.erb
<% @title = "New Ingredient" %>
<%= render 'shared/page_title', title: "Enter a new ingredient" %>

<%= render 'form' %>

app/views/fixings/show.html.erb
<% @title = "#{@fixing.name} Recipe Meals" %>
<%= render 'shared/page_title', title: "#{@fixing.name}" %>

<% if @fixing.recipes.count != 0 %>
  <h4 align="center">Recipe's containing <%= @fixing.name %></h4>
  <div align="center">
    <%= will_paginate @fixing_recipes %>
  </div>
  <%= render 'recipes/recipe', obj: @fixing_recipes %>
  <div align="center">
    <%= will_paginate @fixing_recipes %>
  </div>
<% else %>
  <h4 align="center">No recipes yet!</h4>
<% end %>