config/routes.rb
Rails.application.routes.draw do
  
  # Index root path
  root "pages#home"
  # Setting get of pages/home with controller
  get 'pages/home', to: 'pages#home'
  
  # Nested routes Recipes and then Comments inside
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  # Signup path with Chefs controller
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  # Session Controller routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Ingredient route minus the destroy action in Fixings controller
  resources :fixings, except: [:destroy]
  
  # Setting up Action Cable server
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :ingredients, presence: true, length: { minimum: 5, maximum: 1500 }
  validates :directions, presence: true, length: { minimum: 5, maximum: 1500 }
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_fixings
  has_many :fixings, through: :recipe_fixings
  has_many :comments, dependent: :destroy
  
  def self.search(term, page)
    if term
      where('lower(name) LIKE ? OR lower(ingredients) LIKE ?', "%#{term.downcase}%", "%#{term.downcase}%").paginate(page: page, per_page: 10)
    else
      paginate(page: page, per_page: 10)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
      @recipes = Recipe.search(params[:term], params[:page])
  end
  
  def show
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
    @maximum_length = Recipe.validators_on( :ingredients ).second.options[:maximum]
    @max_length = Recipe.validators_on( :directions ).second.options[:maximum]
  end
  
  def edit
    
  end
  
  def create
    @recipe = Recipe.new(recipe_param)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def update
    if @recipe.update(recipe_param)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted successfully!"
    redirect_to recipes_path
  end
  
  private
  
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end
  
    def recipe_param
      params.require(:recipe).permit(:name, :ingredients, :directions, fixing_ids: [])
    end
    
    def require_same_user
      if current_chef != @recipe.chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own recipes"
        redirect_to recipes_path
      end
    end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>
<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of Recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :ingredients %>
        </div>
        <div class="col-md-3">
          <%= f.text_area :ingredients, maxlength: @maximum_length, id: 'ingredients', rows: 8, class: "form-control", placeholder: "Enter ingredients for the recipe" %>
          Chars left: <span id="counter" data-maximum-length="<%= @maximum_length %>"><%= @maximum_length %></span>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :directions %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :directions, maxlength: @max_length, id: 'directions', rows: 8, class: "form-control", placeholder: "Enter cooking instructions" %>
          Chars left: <span id="counter2" data-maximum-length="<%= @max_length %>"><%= @max_length %></span>
        </div>
      </div>
       <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :fixing_ids, Fixing.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var ingredients = $("#ingredients");
    var counter     = $("#counter");
    var max_length  = counter.data("maximum-length");
      ingredients.keyup(function() {
          counter.text(max_length - $(this).val().length);
      });
  });
  
  $(document).ready(function() {
      var directions = $("#directions");
      var counter     = $("#counter2");
      var max_length  = counter.data("maximum-length");
      
      directions.keyup(function() {
          counter.text(max_length - $(this).val().length);
      });

    });
</script>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.directions, length: 150) %></p>
      <% if recipe.fixings.any? %>
        <p> Ingredients: <%= render recipe.fixings %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created
        <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
                        | <%= pluralize(recipe.comments.count, 'Comment') %></small></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-xlarge" %>
          <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete,
                                        data: { confirm: "Are you sure you want to delete this recipe?" },
                                        class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
  
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit an existing recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<% @title = "Recipes for Healthy Meals" %>
<%= render 'shared/page_title', title: "All Recipes"  %>

<div align="center">
  <%= will_paginate  %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<% @title = @recipe.name %>
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <h4 class="left ingredients"><strong>Ingredients: </strong></h4>
  <%= simple_format(@recipe.ingredients) %>
  <hr />
  <h4 class="center directions"><strong>Cooking Instructions: </strong></h4>
  <%= simple_format(@recipe.directions) %>
  <hr />
  <% if @recipe.fixings.any? %>
    <p>Ingredient Tags: <%= render @recipe.fixings %></p>
  <% end %>
  <div class="pull-right">
    <p class="center">
      <em>Created By:</em>
    </p>
    <p class="center">
      <%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
    </p>
    <p class="center">
      <small><%= @recipe.chef.chefname.capitalize %></small>
      <div class="pull-right"><%= time_ago_in_words(@recipe.created_at) %> ago</div>
    </p>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-xlarge" %>
      <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                        data: { confirm: "Are you sure you want to delete this recipe?" },
                                        class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments:</h3>
      <hr />
      <%= form_for([@recipe, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :comment_text, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :comment_text, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>

<% end %>

<% if @recipe.comments.count != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>