config/routes.rb
Rails.application.routes.draw do
  
  # Index root path
  root "pages#home"
  # Setting get of pages/home with controller
  get 'pages/home', to: 'pages#home'
  
  # Nested routes Recipes and then Comments inside
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  # Signup path with Chefs controller
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  # Session Controller routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Ingredient route minus the destroy action in Fixings controller
  resources :fixings, except: [:destroy]
  
  # Setting up Action Cable server
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/views/pages/home.html.erb
<div class="jumbotron center" title="Pantry Chefs">
  <h1>Welcome to Pantry Chefs</h1>
  <h2>Healthy Meals & Dinner Ideas</h2>
  <p><%= link_to "Signup to add recipes", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %></p>
</div>

<!-- Example row of columns -->
<div class="row">
  <div class="col-lg-4">
    <h2>Explore Recipes</h2>
    <p>We have a ton of recipes for you to explore, not sure about the app yet? Don't worry, just view as a guest. We're sure you'll come back to signup at a later time.</p>
    <p><%= link_to "View all recipes as a Guest!", recipes_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
  <div class="col-lg-4">
    <h2>Unlock all features!</h2>
    <p>Signup for the app and unlock all it's magic. Create and share recipes, hangout with other Chefs in the ChefChat, comment on recipes you have tried out, like/dislike and much much more!</p>
    <p><%= link_to "Signup for an account", signup_path, class: "btn btn-primary btn-xlarge" %></p>
 </div>
  <div class="col-lg-4">
    <h2>Have an ingredient, need ideas?</h2>
    <p>View our ingredients listing page and select and ingredient that you have, to view recipes associated with it for cooking ideas!</p>
    <p><%= link_to "View ingredient listing", fixings_path, class: "btn btn-primary btn-xlarge" %></p>
  </div>
</div>