config/routes.rb
Rails.application.routes.draw do
  
  # Index root path
  root "pages#home"
  # Setting get of pages/home with controller
  get 'pages/home', to: 'pages#home'
  
  # Nested routes Recipes and then Comments inside
  resources :recipes do
    resources :comments, only: [:create]
  end
  
  # Signup path with Chefs controller
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  # Session Controller routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Ingredient route minus the destroy action in Fixings controller
  resources :fixings, except: [:destroy]
  
  # Setting up Action Cable server
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/views/layouts/_footer.html.erb
<!-- Social Footer, Colour Matching Icons -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <hr>
        <div class="text-center center-block">
            <p class="txt-railway">- Find Us Online! -</p>
            <br />
              <a href="https://www.facebook.com/pantrychefs/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
	            <a href="#"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
	            <a href="#"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
	            <a href="mailto:goodeats.appowner@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>
    <hr>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <%= msg %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pantry Chefs", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><%= link_to "All Recipes", recipes_path %></li>
        <!-- Only allows logged in users to view Recipe Actions -->
          <% if logged_in? %>
          <li><%= link_to "Chef Chat", chat_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create a new Recipe", new_recipe_path %></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "All Ingredients", fixings_path %></li>
              <% Fixing.all.each do |fixing| %>
                <li><%= link_to fixing.name.capitalize, fixing_path(fixing) %></li>
              <% end %>
              <% if logged_in? && current_chef.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "New Ingredient", new_fixing_path %></li>
              <% end %>
            </ul>
          </li>
      </ul>
      <%= form_tag(recipes_path, method: :get, class: 'navbar-form navbar-left') do %>
      <%= text_field_tag :term, params[:term], class: 'form-control', placeholder: 'Search'  %>
      <%= submit_tag "Submit", class: 'btn btn-default', name: nil %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.capitalize %>'s Profile <%= "admin" if current_chef.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", chef_path(current_chef) %></li>
              <li><%= link_to "Edit your profile", edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Pantry Chefs: Healthy Meals & Dinner Ideas" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Pantry Chefs is your source for Healthy Meals and great Dinner Ideas! Vegetarian recipes and recipes with meat the whole food spectrum! Need a dinner recipe for cooking search by ingredients!">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>